[package]
name = "georaster"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2021"

description = "Rust library for accessing geospatial raster images."
homepage = "https://github.com/pka/georaster"
repository = "https://github.com/pka/georaster"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["tiff", "geo"]
exclude = [
    "data",    
]

[dependencies]
tiff = "0.7.3"

[dev-dependencies]
image = "0.24.5"
